### ISSUE TITLE
possible issue with ignore route

### ISSUE THREAD

**Issue by tacman** [inspector-apm/inspector-symfony#37]
![image](https://github.com/user-attachments/assets/ca840c18-3ffe-4333-87a6-8e528e939034)

But my config is from the recipe:

```yaml
inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    ignore_routes:
        - '_wdt'
        - '_profiler'
        - '_profiler_home'
        - '_profiler_search'
        - '_profiler_search_bar'
        - '_profiler_phpinfo'
        - '_profiler_search_results'
        - '_profiler_open_file'
        - '_profiler_router'
        - '_profiler_exception'
        - '_profiler_exception_css'
    ignore_commands:
        - 'doctrine:migration:migrate'
        - 'd:m:m'
        - 'debug:autowiring'
        - 'debug:config'
  ```

On a related note, what about ignore_route?  And can the ignore_url values be wildcards?
