### ISSUE TITLE
error when inspector is disabled

### ISSUE THREAD

**Issue by tacman** [inspector-apm/inspector-symfony#39]
![image](https://github.com/user-attachments/assets/d52af0a8-d788-4f64-bb3a-a87057c4c93a)

This happens when either the API key is empty (which I think disables the inspector), or when enabled is false:

```yaml
inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    enabled: false
```

 return $this->inspector->transaction(); allows a null return, so should the trait
